### ISSUE TITLE
feat: bootstrap the plugin marketplace catalogue with agent-skills as the first entry

### ISSUE THREAD

**Issue by iangregsondev** [iangregsondev/claude-plugins#1]
## Summary

Make this repo a Claude Code plugin marketplace: a catalogue that ships no plugin code of its own and instead points at each plugin's own repository.

Marketplace name `iangregson-plugins`. First entry is `iangregson-skills`, sourced from [`iangregsondev/agent-skills`](https://github.com/iangregsondev/agent-skills).

## Why

A plugin repo can carry its own marketplace manifest, and that works fine while the repo *is* the one product. It stops scaling the moment there is a second product: every product adds another marketplace for users to add, and `claude plugin marketplace list` grows one line per product rather than one line per author.

A standalone catalogue decouples the two. One marketplace name, added once, forever. Each plugin keeps its own repo, its own release cadence, and its own version history. Adding a plugin later is one more object in a JSON array — no restructuring here and none in the plugin repos.

## Naming

**Marketplace: `iangregson-plugins`** — author-scoped, not topic-scoped. Marketplace names are keys in the user's local `known_marketplaces.json`, so they must be unique per machine but are not registered anywhere central. A topical name would be wrong for a deliberately multi-product catalogue, and a bare `claude-plugins` would collide with every other person who reaches for the obvious.

**Plugins keep the `iangregson-` prefix.** Plugin names are unique per install rather than per marketplace, and the prefix is what separates `iangregson-skills:tdd` from other authors' identically-named skills.

## Design principle: nothing here changes when a plugin changes

The catalogue's job is to survive untouched between plugin *additions*. Any field that tracks a plugin's contents is a reason to commit here when nothing here changed.

| Field | Decision | Reason |
| --- | --- | --- |
| `ref` / `sha` | Omitted | Pinning would mean a commit here for every release in a plugin repo — precisely the coupling this split exists to remove. |
| `description` | Written here, kept generic | Does not inherit from `plugin.json` for a `github` source. See below. |
| `keywords` | Omitted | The churniest field: skill-level specifics that change with every addition. Name plus description carries browse-time search adequately. |
| `category` | Kept | `plugin.json` has no such field, so this is the catalogue's own data rather than a copy, and it does not track contents. |

**The no-pinning tradeoff.** Entries track each plugin repo's default branch, so installs are not reproducible and a bad commit on a plugin's `main` reaches users on update. That is acceptable here because these are first-party repos with CI gating `main`.

**Why the description cannot be omitted.** For a `github` source, `plugin.json` sits inside a repo that is not fetched until install, so an entry without a description renders blank. Verified by inspection: the official catalogue has 286 entries but only 40 local `plugin.json` files, and every entry supplies its own description.

**Why it must stay generic.** Since it has to live here, it must not enumerate skills or categories, or it goes stale on every addition. Personal-collection precedent supports this — `cc-skills` is described as "AI Agent Skills", `obsidian` as "Claude Skills for Obsidian". The enumerated descriptions in the official catalogue belong to vendors describing a fixed product surface, which is not what this is.

## Scope

**In scope**

- `.claude-plugin/marketplace.json` — marketplace name `iangregson-plugins`, owner metadata (`name` + `url`), and a `plugins` array.
- Exactly one entry to start: `iangregson-skills`, with a `github` source pointing at `iangregsondev/agent-skills`.
- README rewritten as install instructions (add the marketplace, then install a plugin) plus a table of catalogued plugins.
- LICENSE.

**Out of scope**

- Any plugin code — skills, commands, agents, hooks. This repo stays a catalogue.
- CI running `claude plugin validate . --strict`. Worth adding, but as a follow-up issue so this one lands as a single reviewable commit.

## Sketch

```json
{
  "name": "iangregson-plugins",
  "owner": {
    "name": "Ian Gregson",
    "url": "https://github.com/iangregsondev"
  },
  "description": "Ian Gregson's Claude Code plugins, each maintained in its own repository.",
  "plugins": [
    {
      "name": "iangregson-skills",
      "source": {
        "source": "github",
        "repo": "iangregsondev/agent-skills"
      },
      "description": "A general-purpose collection of agent skills for everyday development work.",
      "category": "engineering"
    }
  ]
}
```

Field names to be confirmed against the current plugin documentation before merge. This manifest passes `claude plugin validate`, including `--strict`.

## Acceptance criteria

- [ ] `claude plugin validate . --strict` passes.
- [ ] `claude plugin marketplace add iangregsondev/claude-plugins` succeeds from a clean install.
- [ ] `claude plugin marketplace list` shows an `iangregson-plugins` entry.
- [ ] Browsing the marketplace shows the description for `iangregson-skills`.
- [ ] `claude plugin install iangregson-skills@iangregson-plugins` resolves from GitHub and all eight skills load in a new session.
- [ ] The repo contains no plugin code — only the manifest, README, and LICENSE.
- [ ] Adding a skill to `agent-skills` requires no commit in this repo.

## Sequencing

This repo must be live and verified before `iangregsondev/agent-skills` drops its own `.claude-plugin/marketplace.json`, or there is a window in which the old `iangregson` marketplace is gone and nothing has replaced it.

Note that the catalogue's `github` source reads `agent-skills/.claude-plugin/plugin.json`, not its `marketplace.json` — so removing that manifest has no effect on this catalogue.

The user-facing break (the `iangregson` marketplace no longer resolving) is tracked in iangregsondev/agent-skills#56 and documented there as a breaking change.
